### ISSUE TITLE
TypeError: ical2notion() got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by RedmindSlim** [AlexanderDavid/ical2notion#5]
Traceback (most recent call last):
  File "/usr/local/bin/ical2notion", line 11, in <module>
    load_entry_point('ical2notion==0.3.0', 'console_scripts', 'ical2notion')()
  File "/usr/local/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: ical2notion() got an unexpected keyword argument 'verbose'

runned the command:
ical2notion DATABASE_TO_NOTION_PAGE TOKEN ICAL_SCERET_LINK

What am I doing wrong?

**Comment by AlexanderDavid** [comment]
This was an issue with the arguments to the main method and should have been fixed in 4e0d2d6c0bbdf7efffaf7f21c22024c09ccc188c . This new version is also now on pypi.
